# Generated by Django 2.2.6 on 2019-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Be_icon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ball_icon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dat_add',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fb_icon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tweet_icon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='visiteur',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
