# Generated by Django 2.2.6 on 2019-10-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20191025_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
