# Generated by Django 2.2.6 on 2019-10-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
