# Generated by Django 2.2.6 on 2019-10-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_trois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('fb_icon', models.URLField()),
                ('tweet_icon', models.URLField()),
                ('ball_icon', models.URLField()),
                ('Be_icon', models.URLField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('image_1', models.ImageField(upload_to='images')),
                ('image_2', models.ImageField(upload_to='images')),
                ('image_3', models.ImageField(upload_to='images')),
                ('image_4', models.ImageField(upload_to='images')),
                ('image_5', models.ImageField(upload_to='images')),
                ('image_6', models.ImageField(upload_to='images')),
                ('image_7', models.ImageField(upload_to='images')),
                ('image_8', models.ImageField(upload_to='images')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('titre', models.CharField(max_length=250)),
                ('image_fond', models.ImageField(upload_to='images')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
    ]
