# Generated by Django 2.2.6 on 2019-10-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0011_copy_footer_one_footer_trois_footer_two_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
        migrations.DeleteModel(
            name='Copy',
        ),
        migrations.DeleteModel(
            name='Footer_one',
        ),
        migrations.DeleteModel(
            name='Footer_trois',
        ),
        migrations.DeleteModel(
            name='Footer_two',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
