# Generated by Django 2.2.6 on 2019-10-25 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogger', '0012_auto_20191025_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_trois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('fb_icon', models.URLField()),
                ('tweet_icon', models.URLField()),
                ('ball_icon', models.URLField()),
                ('Be_icon', models.URLField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('image_1', models.ImageField(upload_to='images')),
                ('image_2', models.ImageField(upload_to='images')),
                ('image_3', models.ImageField(upload_to='images')),
                ('image_4', models.ImageField(upload_to='images')),
                ('image_5', models.ImageField(upload_to='images')),
                ('image_6', models.ImageField(upload_to='images')),
                ('image_7', models.ImageField(upload_to='images')),
                ('image_8', models.ImageField(upload_to='images')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('titre', models.CharField(max_length=250)),
                ('image_fond', models.ImageField(upload_to='images')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(default='useravatar.png', upload_to='profile/')),
                ('description', models.TextField()),
                ('statut', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('date', models.DateTimeField()),
                ('sujet', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('photo', models.ImageField(default='images/user.jpg', upload_to='images')),
                ('standard', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleCommentaire', to='blogger.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_cat', to='blogger.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
