# Generated by Django 2.2.6 on 2019-10-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0013_auto_20191025_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copy',
        ),
        migrations.DeleteModel(
            name='Footer_one',
        ),
        migrations.DeleteModel(
            name='Footer_trois',
        ),
        migrations.DeleteModel(
            name='Footer_two',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
