# Generated by Django 2.2.6 on 2019-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0014_auto_20191026_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
