# Generated by Django 2.2.6 on 2019-10-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
