# Generated by Django 2.2.6 on 2019-10-29 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
