# Generated by Django 2.2.6 on 2019-10-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0017_commentaire_date_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='date_add',
        ),
    ]
