# Generated by Django 2.2.6 on 2019-10-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0018_auto_20191028_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='validé',
            new_name='valider',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='validé',
            new_name='valider',
        ),
    ]
