# Generated by Django 2.2.6 on 2019-10-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0019_auto_20191028_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valider',
            field=models.CharField(max_length=50),
        ),
    ]
